appName: &APP transientbug
logName: *APP

debug: true
send_email: false

port: 8001
address: 127.0.0.1
use_pool: true
max_connections: 10000

time_format: "MM/DD/YYYY hh:mm a"

files:
  pid: transientbug.pid
  log: transientbug.log
  stderr: transientbug_error.log
  stdout: transientbug_out.log

dirs:
  pid: pid/
  log: logs/
  search_index: s_index/
  templates: views/
  base: /srv/http/transientbug/
  screenshots: /srv/http/transientbug/scrn/
  gifs: /srv/http/transientbug/i/

databases:
  rethink:
    db: transientbug
  redis:
    db: 1
    URL: localhost

downloader:
  log_name: transientbug_downloader

  files:
    pid: tb_downloader.pid
    log: tb_downloader.log
    stderr: tb_downloader_error.log
    stdout: tb_downloader_out.log

  dirs:
    pid: pid/
    log: logs/

emailer:
  log_name: transientbug_emailer

  files:
    pid: tb_emailer.pid
    log: tb_emailer.log
    stderr: tb_emailer_error.log
    stdout: tb_emailer_out.log

  dirs:
    pid: pid/
    log: logs/
