appName: &APP leach
logName: *APP

port: 8000
address: 127.0.0.1

files:
  pid: leach.pid
  log: leach.log
  stderr: error.log
  stdout: out.log

dirs:
  pid: pid/
  log: logs/
  gifs: /srv/http/i/
  screenshots: /srv/http/scrn/

databases:
  rethink:
    db: app
  redis:
    db: 1
    URL: localhost

sockets:
  zeromq:
    URL: tcp://127.0.0.1
    port: 9000

debug: true
