appName: &APP leach
logName: *APP

port: 8000
address: 127.0.0.1

files:
  pid: pid/leach.pid
  log: logs/leach.log
  stderr: logs/error.log
  stdout: logs/out.log

dirs:
  pid: pid/
  log: logs/
  gifs: /srv/http/transientbug/gifs/
  screenshots: /srv/http/transientbug/screenshots/

databases:
  rethink:
    db: app
  couch:
    db: app
    URL: http://localhost
    port: 5984
  redis:
    db: 1
    URL: localhost

sockets:
  URL: tcp://127.0.0.1
  port: 9000

debug: true

baseURL: http://transientBug.com/
