users:
  - username: bug
    password: josh
    groups:
      - admin
      - root

tables:
  - users
  - notes
  - phots
  - maintenance

buckets:
  enable500Error:
    status: true
    name: Enable errors on 500 pages
    description: Enable the display of the server errors on 500 pages

flush:
  users: false
  redis: false
  sessions: true
  buckets: true
