users:
  - username: bug
    password: josh

tables:
  - users

reset_users: true

buckets:
  enable500Error:
    value: true
    name: Enable errors on 500 pages
    description: Enable the display of the server errors on 500 pages
