users:
  - username: bug
    password: josh
    email: joshuaashby@joshashby.com
    groups:
      - root

tables:
  - users
  - notes
  - phots
  - emails
  - requests
  - invites

buckets:
  enable500Error:
    status: false
    name: Enable errors on 500 pages
    description: Enable the display of the server errors on 500 pages

  enablePublicInvites:
    status: true
    name: Enable the public invite page
    description: Allows anyone to request an invite to join the site when on, and opens registration for those invites

flush:
  rethink:
    invites: false
    users: false
    phots: false
    notes: false
    emails: true
    requests: true

  redis:
    session: true
    bucket: false
